/** Single instruction definition shared by MCP surfaces; runtime details: docs/AGENT_ORCHESTRATION.md. */
export const AGENT_ORCHESTRATION_REFERENCE = "Agent orchestration: docs/AGENT_ORCHESTRATION.md.";
export const AGENT_ORCHESTRATION_INSTRUCTIONS = [
  "AGENT_ORCHESTRATION_V1: Before dependent work, require transport success, no MCP isError or application ok:false, expected exit codes and required result fields. Promise fulfillment is not tool success. Stop dependent actions on failure; independent authorized reads may continue.",
  "Classify failures separately as UPSTREAM_AUTO_REVIEW, BACKEND_POLICY, LOCAL_EXEC_POLICY, TRANSPORT, ARGUMENT, AUTH, APPROVAL_PENDING, EXPECTED_REVIEW_BLOCKED or UNKNOWN. Prefer native codes. A policy denial is not a transport retry.",
  "Count equivalent attempts by intended effect, target, authorization state and failure class, not shell syntax or executor. After a denial, do not repackage the same effect through another tool. Reconsider only after a verified relevant prerequisite changes; after a second equivalent policy denial stop that path and report the blocker. New user approval never overrides platform policy.",
  "Before new diagnostic/status work, prefer an available authorized structured tool covering the full semantics. Batch independent known reads/diagnostics within tool limits and preserve per-item errors; do not pre-batch dependent paths or mutations. Shell remains appropriate for authorized compound operations. Structured-tool-first never permits a denied effect through another executor.",
  "Report a hard blocker on a critical subtask immediately, within 60 seconds: last successful step, block source, equivalent attempt count, changed or missing prerequisite, and permitted next action or needed approval. Report operational facts, not internal reasoning. After 3 active minutes without material progress check the subtask; by 5 active minutes produce a status decision. Exclude approval waits, announced long jobs and suspended work; track blocked critical subtasks separately from other productive work. Unchanged polls and repeated errors are not progress. Deduplicate unchanged notifications.",
  "Use existing start/job-id/output tools for potentially long operations instead of synchronous requests near the 120-second transport deadline. Space polls, combine status/output and continue independent work. After an ambiguous mutation/start response, preserve any job id, reconcile job and side effects before any retry; never blindly start replacement work. These rules add no authority and do not change tool policies."
].join(" ");
